<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="com.setl.RESTAPITests.NAV.Update.NavListUpdateAcceptanceTest" tests="5" skipped="0" failures="5" errors="0" timestamp="2017-12-05T17:34:46" hostname="Bills-iMac.local" time="0.031">
  <properties/>
  <testcase name="failToUpdateNavPriceWhenNavIsFinalised" classname="com.setl.RESTAPITests.NAV.Update.NavListUpdateAcceptanceTest" time="0.005">
    <failure message="org.json.JSONException: JSONObject[&quot;jws&quot;] not found." type="org.json.JSONException">org.json.JSONException: JSONObject[&quot;jws&quot;] not found.
	at org.json.JSONObject.get(JSONObject.java:471)
	at io.setl.restapi.client.RestApi.start(RestApi.java:50)
	at com.setl.RESTAPITests.NAV.Update.NavListUpdateAcceptanceTest.failToUpdateNavPriceWhenNavIsFinalised(NavListUpdateAcceptanceTest.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)
</failure>
  </testcase>
  <testcase name="forceUpdateNavPriceWhenNavIsFinalised" classname="com.setl.RESTAPITests.NAV.Update.NavListUpdateAcceptanceTest" time="0.004">
    <failure message="org.json.JSONException: JSONObject[&quot;jws&quot;] not found." type="org.json.JSONException">org.json.JSONException: JSONObject[&quot;jws&quot;] not found.
	at org.json.JSONObject.get(JSONObject.java:471)
	at io.setl.restapi.client.RestApi.start(RestApi.java:50)
	at com.setl.RESTAPITests.NAV.Update.NavListUpdateAcceptanceTest.forceUpdateNavPriceWhenNavIsFinalised(NavListUpdateAcceptanceTest.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)
</failure>
  </testcase>
  <testcase name="UpdateNavFundDate" classname="com.setl.RESTAPITests.NAV.Update.NavListUpdateAcceptanceTest" time="0.004">
    <failure message="org.json.JSONException: JSONObject[&quot;jws&quot;] not found." type="org.json.JSONException">org.json.JSONException: JSONObject[&quot;jws&quot;] not found.
	at org.json.JSONObject.get(JSONObject.java:471)
	at io.setl.restapi.client.RestApi.start(RestApi.java:50)
	at com.setl.RESTAPITests.NAV.Update.NavListUpdateAcceptanceTest.UpdateNavFundDate(NavListUpdateAcceptanceTest.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)
</failure>
  </testcase>
  <testcase name="UpdateNavFundName" classname="com.setl.RESTAPITests.NAV.Update.NavListUpdateAcceptanceTest" time="0.003">
    <failure message="org.json.JSONException: JSONObject[&quot;jws&quot;] not found." type="org.json.JSONException">org.json.JSONException: JSONObject[&quot;jws&quot;] not found.
	at org.json.JSONObject.get(JSONObject.java:471)
	at io.setl.restapi.client.RestApi.start(RestApi.java:50)
	at com.setl.RESTAPITests.NAV.Update.NavListUpdateAcceptanceTest.UpdateNavFundName(NavListUpdateAcceptanceTest.java:105)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)
</failure>
  </testcase>
  <testcase name="createNav" classname="com.setl.RESTAPITests.NAV.Update.NavListUpdateAcceptanceTest" time="0.015">
    <failure message="org.json.JSONException: JSONObject[&quot;jws&quot;] not found." type="org.json.JSONException">org.json.JSONException: JSONObject[&quot;jws&quot;] not found.
	at org.json.JSONObject.get(JSONObject.java:471)
	at io.setl.restapi.client.RestApi.start(RestApi.java:50)
	at com.setl.RESTAPITests.NAV.Update.NavListUpdateAcceptanceTest.createNav(NavListUpdateAcceptanceTest.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)
</failure>
  </testcase>
  <system-out><![CDATA[payload eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJtZXNzYWdlYm9keSI6eyJ1c2VyaWQiOjE5NX0sIm1lc3NhZ2V0eXBlIjoiaW5pdGlhbGlzZSIsInJlcXVlc3RpZCI6MSwidG9rZW4iOiIiLCJ0aW1lc3RhbXAiOjE1MTI0OTUyODY5MTZ9.e4l3-e8pKAJlAUEn1JjPDPcTdsRfn0a60J9W71rAT24
payload eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJtZXNzYWdlYm9keSI6eyJ1c2VyaWQiOjE5NX0sIm1lc3NhZ2V0eXBlIjoiaW5pdGlhbGlzZSIsInJlcXVlc3RpZCI6MSwidG9rZW4iOiIiLCJ0aW1lc3RhbXAiOjE1MTI0OTUyODY5MjB9.9MbFqZTKQ3V6Mp2t_FKTZEDlvtOwW5SZgAwOzVSuULQ
payload eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJtZXNzYWdlYm9keSI6eyJ1c2VyaWQiOjE5NX0sIm1lc3NhZ2V0eXBlIjoiaW5pdGlhbGlzZSIsInJlcXVlc3RpZCI6MSwidG9rZW4iOiIiLCJ0aW1lc3RhbXAiOjE1MTI0OTUyODY5MjV9.FYttP6n07O7wBvL9QVyCOn04qmW3hSE2cZfMicXV49E
payload eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJtZXNzYWdlYm9keSI6eyJ1c2VyaWQiOjE5NX0sIm1lc3NhZ2V0eXBlIjoiaW5pdGlhbGlzZSIsInJlcXVlc3RpZCI6MSwidG9rZW4iOiIiLCJ0aW1lc3RhbXAiOjE1MTI0OTUyODY5Mjh9.muihnwm8ttWc0wZKM4Ebc0GPMb1YcvmWays5L_R3a0A
payload eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJtZXNzYWdlYm9keSI6eyJ1c2VyaWQiOjE5NX0sIm1lc3NhZ2V0eXBlIjoiaW5pdGlhbGlzZSIsInJlcXVlc3RpZCI6MSwidG9rZW4iOiIiLCJ0aW1lc3RhbXAiOjE1MTI0OTUyODY5NDN9.PFueTOcWrdMxC8qgYk_dhojdXWp7ArJ_gdFWoXPJKCs
]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
