<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="APITests.User.Login.loginTest" tests="4" skipped="1" failures="1" errors="0" timestamp="2017-11-28T12:11:54" hostname="Bills-iMac.local" time="3.581">
  <properties/>
  <testcase name="loginFailureWithUnknownUser" classname="APITests.User.Login.loginTest" time="3.003">
    <failure message="org.junit.runners.model.TestTimedOutException: test timed out after 3000 milliseconds" type="org.junit.runners.model.TestTimedOutException">org.junit.runners.model.TestTimedOutException: test timed out after 3000 milliseconds
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:997)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
	at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:231)
	at APITests.User.Login.loginTest.loginFailureWithUnknownUser(loginTest.java:103)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)
</failure>
  </testcase>
  <testcase name="loginSuccessWithValidCredentials" classname="APITests.User.Login.loginTest" time="0.529"/>
  <testcase name="enumerationTest" classname="APITests.User.Login.loginTest" time="0.0">
    <skipped/>
  </testcase>
  <testcase name="loginFailureWithInvalidCredentials" classname="APITests.User.Login.loginTest" time="0.048"/>
  <system-out><![CDATA[Sending message :153 bytes
message : {"RequestID":1001,"Version":2,"Request":"startRequest","Data":"e4e94a9117aa4ab61cb63ed4071f1c095e85c4f1e4114c5557c146cc00065436","MessageType":"Response"}
res::a7c17d8a665d84d233f1da57e6ba25657fa0770490d5704450669d634895ce72
Sending message :320 bytes
Sending message :153 bytes
message : {"RequestID":1001,"Version":2,"Request":"startRequest","Data":"f35b08f25f3a17eaa279e618385d27712ab8f8a5cb10350c3b50f4e08418ce48","MessageType":"Response"}
res::7631398b72f95c61007b9bdec6608e9a7ba1b406c5d411ba3f2b50c5d4b0b508
Sending message :320 bytes
message : {"Status":"OK","Data":[{"Token":"50f360e3806e92213bf3c1cebb8c6151cba9a2313edef030cc8ae86bf75f6031","Status":"OK","Message":"","UserName":"Emmanuel","UserID":4,"EMailAddress":"emmanuel.rodriguez@setl.io","useTwoFactor":0,"copyMailToEmail":1,"admin":1,"userType":15,"accontID":1,"accountName":"SETL Private Admin","memberID":1,"last_login":"2017-11-27 17:15:13","apiKey":"gV6Il3IAP0ML1WQ4jNkmYAb5FRExrAfWcGCaKzYMQ24=","investorType":null,"platformAddr":"1LsKRrgh2ewD9aA3jMYEqKVgYLQwhQp7gG","defaultAddress":"13jF8jCPmxJi6HBtaqxGyn8GLPcDj1VrJX","defaultWalletID":null}],"MessageType":"Response","Request":"login","RequestID":1002,"Version":2}
Sending message :153 bytes
message : {"RequestID":1001,"Version":2,"Request":"startRequest","Data":"39818a77e22c19ee878e77c32d398e144117ca17d7e390b42285cd023f391036","MessageType":"Response"}
res::bc2bb2901090e1100fc7cea68b12a7e3e18ce34cd7c92dfa49baf17c9a4137d8
Sending message :320 bytes
message : {"Status":"Fail","Data":[{"Token":"fail","Status":"Fail","Message":"","UserName":"","UserID":0,"EMailAddress":"","useTwoFactor":0,"copyMailToEmail":0,"admin":0,"userType":0,"accontID":0,"accountName":"","memberID":0,"last_login":null,"apiKey":null,"investorType":0,"platformAddr":"","defaultAddress":"","defaultWalletID":0}],"MessageType":"Response","Request":"login","RequestID":1002,"Version":2}
]]></system-out>
  <system-err><![CDATA[ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console.
2017-11-28 12:11:54.109:INFO::pool-2-thread-1: Logging initialized @5762ms to org.eclipse.jetty.util.log.StdErrLog
]]></system-err>
</testsuite>
