<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="src.RESTAPITests.NAV.Fetch.NavListAcceptanceTest" tests="3" skipped="0" failures="3" errors="0" timestamp="2017-11-28T12:11:58" hostname="Bills-iMac.local" time="0.153">
  <properties/>
  <testcase name="getValidNavList" classname="src.RESTAPITests.NAV.Fetch.NavListAcceptanceTest" time="0.082">
    <failure message="org.json.JSONException: JSONObject[&quot;jws&quot;] not found." type="org.json.JSONException">org.json.JSONException: JSONObject[&quot;jws&quot;] not found.
	at org.json.JSONObject.get(JSONObject.java:471)
	at io.setl.restapi.client.RestApi.start(RestApi.java:50)
	at src.RESTAPITests.NAV.Fetch.NavListAcceptanceTest.getValidNavList(NavListAcceptanceTest.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)
</failure>
  </testcase>
  <testcase name="getValidNavListUsingEmptyStringForDate" classname="src.RESTAPITests.NAV.Fetch.NavListAcceptanceTest" time="0.041">
    <failure message="org.json.JSONException: JSONObject[&quot;jws&quot;] not found." type="org.json.JSONException">org.json.JSONException: JSONObject[&quot;jws&quot;] not found.
	at org.json.JSONObject.get(JSONObject.java:471)
	at io.setl.restapi.client.RestApi.start(RestApi.java:50)
	at src.RESTAPITests.NAV.Fetch.NavListAcceptanceTest.getValidNavListUsingEmptyStringForDate(NavListAcceptanceTest.java:67)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)
</failure>
  </testcase>
  <testcase name="getValidNavListUsingNullForDate" classname="src.RESTAPITests.NAV.Fetch.NavListAcceptanceTest" time="0.03">
    <failure message="org.json.JSONException: JSONObject[&quot;jws&quot;] not found." type="org.json.JSONException">org.json.JSONException: JSONObject[&quot;jws&quot;] not found.
	at org.json.JSONObject.get(JSONObject.java:471)
	at io.setl.restapi.client.RestApi.start(RestApi.java:50)
	at src.RESTAPITests.NAV.Fetch.NavListAcceptanceTest.getValidNavListUsingNullForDate(NavListAcceptanceTest.java:132)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)
</failure>
  </testcase>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
